# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'rememberme' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rememberme
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'paper-onboarding', '~> 2.0.0'

end
